from setuptools import setup, find_namespace_packages

setup(
    name='personal_assistant',
    version='0.0.1',
    description='Console personal assistant bot. It help you in you difficult routine',
    author='SCARAB sytems company',
    author_email='pentagon846@gmail.com',
    url='http://https://github.com/pentagon846',
    readme='README.md',
    requires_python='>=3.10',
    license='MIT',
    include_package_data=True,
    packages=find_namespace_packages(),
    install_requires=['questionary==2.0.1',
                      'requests==2.31.0',
                      'googletrans==4.0.0rc1',
                      'pathlib==1.0.1',
                      'prompt-toolkit==3.0.36',
                      'tqdm==4.66.1',
                      'certifi==2023.11.17',
                      'chardet==3.0.4',
                      'charset-normalizer==3.3.2',
                      'colorama==0.4.6',
                      'h11==0.14.0',
                      'h2==3.2.0',
                      'hpack==3.0.0',
                      'hstspreload==2023.1.1',
                      'httpcore==1.0.2',
                      'httpx==0.26.0',
                      'hyperframe==5.2.0',
                      'idna==2.10',
                      'markdown-it-py==3.0.0',
                      'mdurl==0.1.2',
                      'Pygments==2.17.2',
                      'rfc3986==1.5.0',
                      'rich==13.7.0',
                      'sniffio==1.3.0',
                      'termcolor==2.4.0',
                      'urllib3==2.1.0',
                      'wcwidth==0.2.12',
                      'datetime==5.4',
                      ],

    entry_points={'console_scripts': ['scarab_helper=our_project.main:start_menu']}
)
